// <auto-generated />
namespace RpshopingMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletepid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletepid));
        
        string IMigrationMetadata.Id
        {
            get { return "201903130809170_deletepid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
