// <auto-generated />
namespace RpshopingMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adduopenid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduopenid));
        
        string IMigrationMetadata.Id
        {
            get { return "201905041309120_adduopenid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
